### PR TITLE
Redesign How Pipeline Works  page

### PR DESCRIPTION
**Pull request by sparrowsl**

### CODE REVIEW

**Comment by saidubundukamara** [comment]
You might want to take a look at this 
`error during build:
Could not resolve "../../../lib/Journey.svelte" from "src/routes/resources/digital-public-good/+page.svelte"
file: /vercel/path0/src/routes/resources/digital-public-good/+page.svelte`

Deployment failed on vercel deployment

**Comment by sparrowsl** [comment]
has been fixed

**Comment by saidubundukamara** [comment]
It good now, but the product/design team did some changes to this UI and merging this will alter the current design.
So i'm closing this issue now.

**Comment by saidubundukamara** [comment]
It good now, but the product/design team did some changes to this UI and merging this will alter the current design.
So i'm closing this issue now.

**Pull request closed without merging**
